/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sha1BruteForce;

import java.awt.Color;
import java.io.UnsupportedEncodingException;
import java.lang.reflect.Array;
import java.math.BigInteger;
import java.security.NoSuchAlgorithmException;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author benja
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        clearText_btn = new javax.swing.JButton();
        generateSHA1_btn = new javax.swing.JButton();
        pwdLen_txt = new javax.swing.JTextField();
        setABrute_btn = new javax.swing.JButton();
        setBBrute_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputText = new javax.swing.JTextField();
        bruteForceText_btn = new javax.swing.JButton();
        bruteForceBCH_btn = new javax.swing.JButton();
        inputBCH = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputBCH = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        outputText = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        charSetZeroNine_btn = new javax.swing.JButton();
        charSetAToZ_btn = new javax.swing.JButton();
        charAZZeroNine_btn = new javax.swing.JButton();
        charSet_Label = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        inputSHA1_txtb1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cleartxt_btn = new javax.swing.JButton();
        clearBCH_btn = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clearText_btn.setText("Clear");
        clearText_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearText_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clearText_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        generateSHA1_btn.setText("SHA-1");
        generateSHA1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateSHA1_btnActionPerformed(evt);
            }
        });
        getContentPane().add(generateSHA1_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        pwdLen_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdLen_txtActionPerformed(evt);
            }
        });
        getContentPane().add(pwdLen_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 100, -1));

        setABrute_btn.setText("Set A Brute Text Passwords");
        setABrute_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setABrute_btnActionPerformed(evt);
            }
        });
        getContentPane().add(setABrute_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        setBBrute_btn.setText("Set B Brute BCH");
        setBBrute_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setBBrute_btnActionPerformed(evt);
            }
        });
        getContentPane().add(setBBrute_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 680, 34));

        jLabel1.setText("Input to hash");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setText("SHA1 Output");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel3.setText("Brute force SHA1 Hash Arrays in code");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        inputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTextActionPerformed(evt);
            }
        });
        getContentPane().add(inputText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 290, -1));

        bruteForceText_btn.setText("Brute Force Text");
        bruteForceText_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bruteForceText_btnActionPerformed(evt);
            }
        });
        getContentPane().add(bruteForceText_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 139, -1));

        bruteForceBCH_btn.setText("Brute force BCH");
        bruteForceBCH_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bruteForceBCH_btnActionPerformed(evt);
            }
        });
        getContentPane().add(bruteForceBCH_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 139, -1));
        getContentPane().add(inputBCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 291, -1));

        outputBCH.setColumns(20);
        outputBCH.setRows(5);
        jScrollPane3.setViewportView(outputBCH);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 391, 30));

        outputText.setColumns(20);
        outputText.setRows(5);
        jScrollPane4.setViewportView(outputText);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 391, 30));

        jLabel6.setText("SHA1 Input");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel7.setText("Output: Plain Text Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jLabel8.setText("Output: Plain Text Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        jLabel9.setText("SHA1 Input");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel10.setText("==========================================================Generate SHA1==============================================================");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel11.setText("==========================================================Bruteforce SHA1 Passwords==============================================================");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jLabel12.setText("===========================================================Bruteforce SHA1 Hash Arrays=====================================================================");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 360, -1, -1));

        jLabel13.setText("===========================================================Bruteforce SHA1 BCH=====================================================================");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        charSetZeroNine_btn.setText("0-9");
        charSetZeroNine_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charSetZeroNine_btnActionPerformed(evt);
            }
        });
        getContentPane().add(charSetZeroNine_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        charSetAToZ_btn.setText("A-Z");
        charSetAToZ_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charSetAToZ_btnActionPerformed(evt);
            }
        });
        getContentPane().add(charSetAToZ_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        charAZZeroNine_btn.setText("A-Z, 0-9");
        charAZZeroNine_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charAZZeroNine_btnActionPerformed(evt);
            }
        });
        getContentPane().add(charAZZeroNine_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        charSet_Label.setForeground(new java.awt.Color(235, 0, 0));
        charSet_Label.setText("Char set NOT selected");
        getContentPane().add(charSet_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        jLabel15.setText("Choose Char set");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel16.setText("Password Length");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        inputSHA1_txtb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSHA1_txtb1ActionPerformed(evt);
            }
        });
        getContentPane().add(inputSHA1_txtb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 166, -1));

        jLabel4.setText("Please Set Password len +1 above the desired password length");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        cleartxt_btn.setText("Clear");
        cleartxt_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleartxt_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cleartxt_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        clearBCH_btn.setText("Clear");
        clearBCH_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBCH_btnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBCH_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Function clears text boxes
    private void clearText_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearText_btnActionPerformed
        pwdLen_txt.setText("");
        display.setText("");
    }//GEN-LAST:event_clearText_btnActionPerformed

    /*
    Function converts a byte array to hex
    Takes an input as a byte array, converts it to hexadecimal 
    returns it as a string
    */
    private static String convertToHex(byte[] data) {
        StringBuffer buf = new StringBuffer();
        for (int i = 0; i < data.length; i++) {
            int halfbyte = (data[i] >>> 4) & 0x0F;
            int two_halfs = 0;
            do {
                if ((0 <= halfbyte) && (halfbyte <= 9)) {
                    buf.append((char) ('0' + halfbyte));
                } else {
                    buf.append((char) ('a' + (halfbyte - 10)));
                }
                halfbyte = data[i] & 0x0F;
            } while (two_halfs++ < 1);
        }
        return buf.toString();
    }

    /*
    Produces a SHA1 hash as output from a given string
    Takes in the input string in parameters and converts to sha1
    returns a SHA1 hash a string
    */
    public static String SHA1(String text)
            throws NoSuchAlgorithmException, UnsupportedEncodingException {
        MessageDigest md;
        md = MessageDigest.getInstance("SHA-1");
        byte[] sha1hash = new byte[40];
        md.update(text.getBytes("iso-8859-1"), 0, text.length());
        sha1hash = md.digest();
        return convertToHex(sha1hash);

    }

    /*
    Button code to produce a SHA1 hash
    returns void
    */
    private void generateSHA1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateSHA1_btnActionPerformed
        String userInput = inputSHA1_txtb1.getText();
        try {
            display.setText("SHA1 hash of string: " + SHA1(userInput));
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_generateSHA1_btnActionPerformed
    /*
    Checks to see if the given input string only contains integers
    returns true if it does and false if it does not
    */
    public static boolean checkIfNumber(String inputString) {
        boolean validIn = true;
        if (inputString.equals("")) {
            return false;
        } else {
            for (int i = 0; i < inputString.length(); i++) {

                if (inputString.charAt(i) != "0".charAt(0) && inputString.charAt(i) != "1".charAt(0) && inputString.charAt(i) != "2".charAt(0) && inputString.charAt(i) != "3".charAt(0)
                        && inputString.charAt(i) != "4".charAt(0) && inputString.charAt(i) != "5".charAt(0) && inputString.charAt(i) != "6".charAt(0) && inputString.charAt(i) != "7".charAt(0)
                        && inputString.charAt(i) != "8".charAt(0) && inputString.charAt(i) != "9".charAt(0)) {
                    validIn = false;
                    break;
                }
            }
        }
        return validIn;
    }

    private void pwdLen_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdLen_txtActionPerformed

    }//GEN-LAST:event_pwdLen_txtActionPerformed

    public boolean pwdCrackedSha = false;

    //============================================Char set============================================
    public ArrayList<String> charSetAZZeroNine = new ArrayList<String>(Arrays.asList("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"));
    public ArrayList<String> charSetZeroNine = new ArrayList<String>(Arrays.asList("0", "1", "2", "3", "4", "5", "6", "7", "8", "9"));
    public ArrayList<String> charSetAZ = new ArrayList<String>(Arrays.asList("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"));
    public ArrayList<String> SHA_ACharSet = new ArrayList<String>();
    public boolean charsetSelected = false;
    //==================================================================================================

    /*
    This function is use to brute force alphanumeric passwords
    Takes the current password, current position, the password length needed to be generated and the sha1 hash that needs to be brute forced as input
    returns error only if the password is not cracked
    */
    String bruteSHA_A(String password, int currentPos, int sizeOfString, String shaToCrack) throws NoSuchAlgorithmException, UnsupportedEncodingException {
        //Generates all possible combitaions of given char set recursivly
        if (currentPos < sizeOfString) {// If the size of the current string is smaller than the current possition then:
            for (int i = 0; i < SHA_ACharSet.size(); i++) {
                if (pwdCrackedSha == false) {// If the password is cracked stop recursion.
                    bruteSHA_A(password + SHA_ACharSet.get(i), currentPos + 1, sizeOfString, shaToCrack); //Recurse and add one charicter to string increment current pos
                }
            }
        } else {
            //System.out.println(password);
            if (shaToCrack.equals(SHA1(password))) {// Checks to see if generated password hash is the same as input password hash if so the password has been found.
                System.out.println("Password Cracked, " + "The Password: " + password);
                pwdCrackedSha = true;// Sets true to prevent further recursion to save time
                passwordText = password;
            }
        }
        return "Error";
    }

    /*
    This function is use to brute force alphanumeric passwords, it takes all hashes in the setA array list and brute forces them in sequentially
    returns void
    */
    private void setABrute_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setABrute_btnActionPerformed
        pwdCrackedSha = false;
        ArrayList<String> setA = new ArrayList<String>(Arrays.asList(
                "c2543fff3bfa6f144c2f06a7de6cd10c0b650cae", "b47f363e2b430c0647f14deea3eced9b0ef300ce",
                "e74295bfc2ed0b52d40073e8ebad555100df1380", "0f7d0d088b6ea936fb25b477722d734706fe8b40",
                "77cfc481d3e76b543daf39e7f9bf86be2e664959", "5cc48a1da13ad8cef1f5fad70ead8362aabc68a1",
                "4bcc3a95bdd9a11b28883290b03086e82af90212", "7302ba343c5ef19004df7489794a0adaee68d285",
                "21e7133508c40bbdf2be8a7bdc35b7de0b618ae4", "6ef80072f39071d4118a6e7890e209d4dd07e504",
                "02285af8f969dc5c7b12be72fbce858997afe80a", "57864da96344366865dd7cade69467d811a7961b"));
        int passwordLen = 7;
        for (int x = 0; x < setA.size(); x++) {//Loop through all password hash to be cracked
            long startTime = System.nanoTime();// Used to record time of completion
            pwdCrackedSha = false;

            for (int i = 0; i < passwordLen; i++) {//Loops to generate passwords up to a password size of 7 
                if (pwdCrackedSha == false) {// Checks to see if password has been cracked yet
                    try {

                        bruteSHA_A("", 0, i, setA.get(x));//Brute force password hash
                        if (pwdCrackedSha == true) {// If successful then
                            long endTime = System.nanoTime();// log time of completion
                            System.out.println("Cracked in: " + (endTime - startTime) + " ns");// Calculate the time it took in nano seconds
                        }

                    } catch (NoSuchAlgorithmException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }

    }//GEN-LAST:event_setABrute_btnActionPerformed

    /*
    Generates last four digits of BCH code, the first 6 digiets are taken in as a string
    Returns the new 10 digit BCH number as a string.
    */
    String gen4(String numberIn) {

        ArrayList<Integer> number = new ArrayList<Integer>();
        for (int i = 0; i < numberIn.length(); i++) {// Add each integer value to an array
            number.add(Integer.parseInt(String.valueOf(numberIn.charAt(i))));
        }
        number.add((4 * number.get(0) + 10 * number.get(1) + 9 * number.get(2) + 2 * number.get(3) + number.get(4) + 7 * number.get(5)) % 11);
        number.add((7 * number.get(0) + 8 * number.get(1) + 7 * number.get(2) + number.get(3) + 9 * number.get(4) + 6 * number.get(5)) % 11);
        number.add((9 * number.get(0) + number.get(1) + 7 * number.get(2) + 8 * number.get(3) + 7 * number.get(4) + 7 * number.get(5)) % 11);
        number.add((number.get(0) + 2 * number.get(1) + 9 * number.get(2) + 10 * number.get(3) + 4 * number.get(4) + number.get(5)) % 11);

        if (number.get(6) == 10 || number.get(7) == 10 || number.get(8) == 10 || number.get(9) == 10) {// if any generated numbers are greater than 10 then the BCH code is invalid
            return "invalid";
        } else {
            StringBuilder newString = new StringBuilder();
            for (int i = 0; i < number.size(); i++) {
                newString.append(number.get(i));
            }

            return String.valueOf(newString);
        }
    }


    /*
    This function is use to brute force BCH codes.
    Takes the current password, current position, the password length needed to be generated and the sha1 hash that needs to be brute forced as input
    returns error if BCH code is not found
    */
    public boolean pwdCrackedShaB = false;

    String bruteSHA_B(String password, int currentPos, int sizeOfString, String shaToCrack) throws NoSuchAlgorithmException, UnsupportedEncodingException {
        ArrayList<String> string = new ArrayList<String>(Arrays.asList("0", "1", "2", "3", "4", "5", "6", "7", "8", "9"));
        //Generates all possible combitaions of given char set recursivly
        if (currentPos < sizeOfString) { // If the size of the current string is smaller than the current possition then: 
            for (int i = 0; i < string.size(); i++) {
                if (pwdCrackedShaB == false) {// If the password is cracked stop recursion.

                    bruteSHA_B(password + string.get(i), currentPos + 1, sizeOfString, shaToCrack);  //Recurse and add one charicter to string, increment current pos.
                }
            }
        } else {
            String number = gen4(password);//Calculate last four digits of BHC code with the 6 generated
            if (number.equals("invalid")) {//If the BCH code is invalid, ignore code

            } else {
                if (shaToCrack.equals(SHA1(String.valueOf(number)))) {//if hashed found BCH code equals given hash, password found, stop recurtion
                    System.out.println("Password Cracked, " + "The Password: " + number);
                    pwdCrackedShaB = true;
                    passwordBCH = number;
                }
            }

        }
        return "Error";
    }

    /*
    This function is use to brute force BCH codes, it takes all hashes in the setB array list and brute forces them in sequentially
    returns void
    */
    private void setBBrute_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setBBrute_btnActionPerformed
        ArrayList<String> setB = new ArrayList<String>(Arrays.asList("902608824fae2a1918d54d569d20819a4288a4e4", "88d0b34055b79644196fce25f876bc1a5ef654d3", "5b8f495b7f02b62eb228c5dbece7c2f81b60b9a3"));
        int passwordLen = 6;
        for (int x = 0; x < setB.size(); x++) {// For each hash in set
            long startTime = System.nanoTime();// Start recording time
            pwdCrackedShaB = false;
            if (pwdCrackedShaB == false) {// If the password has not been found then
                try {
                    bruteSHA_B("", 0, passwordLen, setB.get(x));//Brute force hash
                    if (pwdCrackedShaB == true) {// if password found, record time taken to do so
                        long endTime = System.nanoTime();
                        System.out.println("Cracked in: " + (endTime - startTime) + " ns");
                    }

                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_setBBrute_btnActionPerformed
    public String passwordText = "";

    /*
    This function is use to brute force alphanumeric passwords, it takes an indervidual hash from user input and tries to crack it using the bruteSHA_A function
    returns void
    */
    private void bruteForceText_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bruteForceText_btnActionPerformed
        pwdCrackedSha = false;
        String inputHash = inputText.getText();
        if (charsetSelected == true) {// Makes sure a user has selected a char set
            long startTime = System.nanoTime();// Used to record time of completion
            pwdCrackedSha = false;
            String passwordLenStr = pwdLen_txt.getText();// Get user inputed password length
            if (checkIfNumber(passwordLenStr) == true) {// Checks if the user inputed password len is actually a number
                int passwordLen = Integer.parseInt(passwordLenStr); //Set password length
                for (int i = 0; i < passwordLen; i++) {//Loops to generate passwords up to a password size of 7 
                    if (pwdCrackedSha == false) {// Checks to see if password has been cracked yet
                        try {
                            bruteSHA_A("", 0, i, inputHash);

                            if (pwdCrackedSha == true) {// If successful then
                                long endTime = System.nanoTime();// log time of completion
                                System.out.println("Cracked in: " + (endTime - startTime) + " ns");// Calculate the time it took in nano seconds
                                outputText.setText("Password: " + passwordText + " Time: " + (endTime - startTime) + " ns");//Brute force password hash
                            }

                        } catch (NoSuchAlgorithmException | UnsupportedEncodingException ex) {
                            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            } else {
                outputText.setText("Invalid Password Length");
            }
        } else {
            outputText.setText("Char Set Not Selected");
        }
    }//GEN-LAST:event_bruteForceText_btnActionPerformed
    public String passwordBCH = "";

    /*
    This function is use to brute force BCH codes, it takes an indervidual hash from user input and tries to crack it using the bruteSHA_B function
    returns void
    */
    private void bruteForceBCH_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bruteForceBCH_btnActionPerformed
        String inputHash = inputBCH.getText();
        int passwordLen = 6;
        long startTime = System.nanoTime();// Start recording time
        pwdCrackedShaB = false;
        if (pwdCrackedShaB == false) {// If the password has not been found then
            try {
                bruteSHA_B("", 0, passwordLen, inputHash);//Brute force hash
                if (pwdCrackedShaB == true) {// if password found, record time taken to do so
                    long endTime = System.nanoTime();
                    System.out.println("Cracked in: " + (endTime - startTime) + " ns");
                    outputBCH.setText("Password: " + passwordBCH + " Time: " + (endTime - startTime) + " ns");
                }

            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bruteForceBCH_btnActionPerformed

    private void inputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTextActionPerformed

    private void inputSHA1_txtb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSHA1_txtb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSHA1_txtb1ActionPerformed
    /*
    Sets charset to 0-9
    */
    private void charSetZeroNine_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charSetZeroNine_btnActionPerformed
        SHA_ACharSet = charSetZeroNine;
        charSet_Label.setText("Charset Selected: 0-9");
        charSet_Label.setForeground(Color.green);
        charsetSelected = true;
    }//GEN-LAST:event_charSetZeroNine_btnActionPerformed
    /*
    Sets charset to A-Z
    */
    private void charSetAToZ_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charSetAToZ_btnActionPerformed
        SHA_ACharSet = charSetAZ;
        charSet_Label.setText("Charset Selected: A-Z");
        charSet_Label.setForeground(Color.green);
        charsetSelected = true;
    }//GEN-LAST:event_charSetAToZ_btnActionPerformed
    /*
    Sets charset to alphanumerical
    */
    private void charAZZeroNine_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charAZZeroNine_btnActionPerformed
        SHA_ACharSet = charSetAZZeroNine;
        charSet_Label.setText("Charset Selected: A-Z,0-9");
        charSet_Label.setForeground(Color.green);
        charsetSelected = true;
    }//GEN-LAST:event_charAZZeroNine_btnActionPerformed
    /*
    Clears text boxes, resets program parameters for brute forcing text/numerical/Alphanumerical passwords
    */
    private void cleartxt_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleartxt_btnActionPerformed
        inputText.setText("");
        outputText.setText("");
        pwdLen_txt.setText("");
        SHA_ACharSet = new ArrayList<String>();
        charSet_Label.setText("Char set NOT selected");
        charSet_Label.setForeground(Color.red);
        charsetSelected = false;
    }//GEN-LAST:event_cleartxt_btnActionPerformed
    /*
    Clears text boxes, resets program parameters for brute forcing BCH(10,6) codes
     */
    private void clearBCH_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBCH_btnActionPerformed
        inputBCH.setText("");
        outputBCH.setText("");
    }//GEN-LAST:event_clearBCH_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bruteForceBCH_btn;
    private javax.swing.JButton bruteForceText_btn;
    private javax.swing.JButton charAZZeroNine_btn;
    private javax.swing.JButton charSetAToZ_btn;
    private javax.swing.JButton charSetZeroNine_btn;
    private javax.swing.JLabel charSet_Label;
    private javax.swing.JButton clearBCH_btn;
    private javax.swing.JButton clearText_btn;
    private javax.swing.JButton cleartxt_btn;
    private javax.swing.JTextArea display;
    private javax.swing.JButton generateSHA1_btn;
    private javax.swing.JTextField inputBCH;
    private javax.swing.JTextField inputSHA1_txtb1;
    private javax.swing.JTextField inputText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea outputBCH;
    private javax.swing.JTextArea outputText;
    private javax.swing.JTextField pwdLen_txt;
    private javax.swing.JButton setABrute_btn;
    private javax.swing.JButton setBBrute_btn;
    // End of variables declaration//GEN-END:variables
}
