package isbnAndLuhnMain;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;

/**
 *
 * @author benja
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VerifyISBN_btn = new javax.swing.JButton();
        clearAll_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        VeriftSixteenDigit_btn = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VerifyISBN_btn.setText("Verify ISBN");
        VerifyISBN_btn.setActionCommand("Clear");
        VerifyISBN_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyISBN_btnActionPerformed(evt);
            }
        });

        clearAll_btn.setText("Clear All");
        clearAll_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAll_btnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        VeriftSixteenDigit_btn.setText("Verify Luhn");
        VeriftSixteenDigit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeriftSixteenDigit_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Luhn 16 digit card");

        jLabel2.setText("ISBN 10 digit");

        jLabel3.setText("Result");

        jLabel4.setText("Verify ISBN and Luhn numbers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VerifyISBN_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearAll_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VeriftSixteenDigit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(clearAll_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(VerifyISBN_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VeriftSixteenDigit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    Clears all text fields and areas
    returns void
    */
    private void clearAll_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAll_btnActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");

    }//GEN-LAST:event_clearAll_btnActionPerformed
    /*
    Verifies a given ISBN number given in parameters as an ArrayList<Integer>
    Outputs vadility to user interface
    returns void
    */
    public void verifyISBN(ArrayList<Integer> number){
        // calculate result of formulae 
        int result = (number.get(0)+2*number.get(1)+3*number.get(2)+4*number.get(3)+5*number.get(4)+6*number.get(5)+7*number.get(6)+8*number.get(7)+9*number.get(8)+10*number.get(9)) % 11;
        //If the result is 0 then it is a valid ISBN
        if (result == 0){
            jTextArea1.setText("Valid ISBN");
        }else{
            jTextArea1.setText("Not Valid ISBN");
        }
    }
    /*
    Verifies a given Luhn credit card number given in parameters as an ArrayList<Integer>
    Outputs vadility to user interface
    returns void
    */
    public void verifyLuhn(ArrayList<Integer> cardNumber){
        for (int x = 0; x < 16; x++){//For all sixteen digits of the credit card number
            if ((x % 2) == 0){// of the modulus of that diget is 2 then
                int NewNumber = cardNumber.get(x) + cardNumber.get(x);//Double the digit
                if (NewNumber >= 10){//IF it is greater than 10 then minus 9 to make it smaller than 10
                    cardNumber.set(x,  NewNumber - 9);
                }else{//Else set the new digit as a digit in card number
                     cardNumber.set(x,  NewNumber);
                }
                
            }
         
        }
        
        int result = 0;
        //Add up all digits in card number
        for (int x = 0; x < 16; x++){
            result = result + cardNumber.get(x);
        }
        
        int finalResult;
        finalResult = result % 10;// mod added number by 10
        
        if (finalResult == 0){// IF mod is zero it is a valid card number
            jTextArea1.setText("Valid Luhn");
        }else{
            jTextArea1.setText("Not Valid Luhn");
        }
    }
    /*
    uses verifyISBN to verify a given ISBN number, also checks user input for errors
    Outputs vadility of user input to user interface
    returns void
    */
    private void VerifyISBN_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyISBN_btnActionPerformed
        ArrayList<Integer> number = new ArrayList<Integer>();
        String inputString;
	inputString = jTextField1.getText();
        boolean validIn = true;
        //Code validates that the number has no other charicters than numbers and is of the correct length
        for (int i = 0; i < inputString.length(); i++){
            if (inputString.charAt(i) != "0".charAt(0) && inputString.charAt(i) != "1".charAt(0) && inputString.charAt(i) != "2".charAt(0) && inputString.charAt(i) != "3".charAt(0) &&
                inputString.charAt(i) != "4".charAt(0) && inputString.charAt(i) != "5".charAt(0) && inputString.charAt(i) != "6".charAt(0) && inputString.charAt(i) != "7".charAt(0)         
                && inputString.charAt(i) != "8".charAt(0) && inputString.charAt(i) != "9".charAt(0) && inputString.charAt(i) != "-".charAt(0)
                ){
                    System.out.println(inputString.charAt(i));
                    validIn = false;
                    jTextArea1.setText("Error: input: invalid input");
                } 
            if(validIn == false){
                break;
            }else{
                if (inputString.charAt(i) != "-".charAt(0)){
                        number.add(Integer.parseInt(String.valueOf(inputString.charAt(i)))); 
                } 
            }  
        }
        if(number.size() != 10 && validIn == true){
            jTextArea1.setText("Error: input: too many numbers/Too few numbers");
            System.out.println(number.size());
        }else if(number.size() == 10 && validIn == true){
            verifyISBN(number);//If all checks pass then calculate if valid
        } 
    }//GEN-LAST:event_VerifyISBN_btnActionPerformed
    
    /*
    uses verifyLuhn to verify a given Luhn credit card number, also checks user input for errors
    Outputs vadility of user input to user interface
    returns void
    */
    private void VeriftSixteenDigit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeriftSixteenDigit_btnActionPerformed
        ArrayList<Integer> number = new ArrayList<Integer>();
        String inputString;
	inputString = jTextField2.getText();
        boolean validIn = true;
        //Code validates that the number has no other charicters than numbers and is of the correct length
        for (int i = 0; i < inputString.length(); i++){
            if (inputString.charAt(i) != "0".charAt(0) && inputString.charAt(i) != "1".charAt(0) && inputString.charAt(i) != "2".charAt(0) && inputString.charAt(i) != "3".charAt(0) &&
                inputString.charAt(i) != "4".charAt(0) && inputString.charAt(i) != "5".charAt(0) && inputString.charAt(i) != "6".charAt(0) && inputString.charAt(i) != "7".charAt(0)         
                && inputString.charAt(i) != "8".charAt(0) && inputString.charAt(i) != "9".charAt(0) && inputString.charAt(i) != "-".charAt(0)
                ){
                    System.out.println(inputString.charAt(i));
                    validIn = false;
                    jTextArea1.setText("Error: input: invalid input");
                } 
            if(validIn == false){
                break;
            }else{
                if (inputString.charAt(i) != "-".charAt(0)){
                        number.add(Integer.parseInt(String.valueOf(inputString.charAt(i)))); 
                } 
            }  
        }
        if(number.size() != 16 && validIn == true){
            jTextArea1.setText("Error: input: too many numbers/Too few numbers");
            System.out.println(number.size());
        }else if(number.size() == 16 && validIn == true){
            verifyLuhn(number);//If all checks pass then calculate if valid
        }
        
        
    }//GEN-LAST:event_VeriftSixteenDigit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VeriftSixteenDigit_btn;
    private javax.swing.JButton VerifyISBN_btn;
    private javax.swing.JButton clearAll_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
